/* Generated by Payload, then edited to disable the playground in production. */
import config from '@payload-config'
import '@payloadcms/next/css'
import { GRAPHQL_PLAYGROUND_GET } from '@payloadcms/next/routes'

// The playground is a dev tool; don't expose it on the public production site.
export const GET =
  process.env.NODE_ENV === 'production'
    ? () => new Response('Not Found', { status: 404 })
    : GRAPHQL_PLAYGROUND_GET(config)
